[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.7.1"
octocrab = "0.43.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_with = "3.9.0"
tokio = {version = "1.38.1", features = ["macros", "rt-multi-thread"]}
